[tool.poetry]
name = "asteroids"
version = "0.1.0"
description = ""
authors = ["Sophia"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"

[tool.poetry.scripts]
asteroids = 'asteroids.main:main'

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
